### ISSUE TITLE
Add support for creating new tables

### ISSUE THREAD

**Issue by Scrounger** [yuweiguocn/GreenDaoUpgradeHelper#12]
Please add support for creating new tables.
At the moment i got all the time error, that temporary table can not create, because the table does not exist.

**Comment by yuweiguocn** [comment]
It's support for creating new tables.This error is no influence.

**Comment by yuweiguocn** [comment]
Please upgrade to version 1.3.0 and try it again.

**Comment by Scrounger** [comment]
Perfect, now it works!

**Comment by changshuai0512** [comment]
加密数据库不支持。。
