### ISSUE TITLE
这种创建临时表来迁移数据和不用这种方法来实现的区别是什么？这种方法有什么好处？

### ISSUE THREAD

**Issue by YangShaoXiong** [yuweiguocn/GreenDaoUpgradeHelper#15]
请教个问题，有关数据升级问题，我一直是在onUpgrade通过比对oldVersion来写SQL语句实现，如下：
public class MySQLiteOpenHelper extends DaoMaster.OpenHelper{

    private static final String TAG = "MySQLiteOpenHelper";

    public MySQLiteOpenHelper(Context context, String name, SQLiteDatabase.CursorFactory factory) {
        super(context, name, factory);
    }

    @Override
    public void onUpgrade(Database db, int oldVersion, int newVersion) {
        super.onUpgrade(db, oldVersion, newVersion);

        Log.d(TAG, "数据库需要升级，上一个数据的版本号为=" + oldVersion);
        switch (oldVersion) {
            case 1:
                // 往Student表里增加age字段
                db.execSQL("alter table STUDENT add column AGE string");
                // 添加User表
                UserDao.createTable(db, false);
                break;
        }
    }
}
我想知道你这种方法和我这种方法有什么区别，好处在哪？还有我这种方法有什么弊端？麻烦在百忙之中帮我解惑一下，提前谢谢你了！

**Comment by yuweiguocn** [comment]
简单，方便！

上面的代码是数据库只改动了一次，并且只改动了一个表，后面数据库的每次升级都需要根据版本做相应处理。
