### ISSUE TITLE
Failed to restore data from temp table

### ISSUE THREAD

**Issue by Bertkiing** [yuweiguocn/GreenDaoUpgradeHelper#16]
Hi , I use your library  to upgrade GreenDaoDB,but I meet a problem:
![err](https://cloud.githubusercontent.com/assets/19733128/21845307/0ea45eec-d82d-11e6-889e-f284ab41b99b.png)
Please to help me , Thanks you!!! 

BTW,friendly remaider:
![note](https://cloud.githubusercontent.com/assets/19733128/21845423/94a432b0-d82d-11e6-9aa7-479f6db46696.png)

I didn't mean any offense,I  just think you should thank more than one ---"GreenDao" ...

**Comment by yuweiguocn** [comment]
Thanks for your reminder!It's all my fault and I already update the README file.

**Comment by Bertkiing** [comment]
I think combine the SQL statement with your library  is the best way!!!  Thank you anyway.
