### ISSUE TITLE
Feature: default value for new columns defined as 'notNull'

### ISSUE THREAD

**Issue by Scrounger** [yuweiguocn/GreenDaoUpgradeHelper#21]
@yuweiguocn 
Could you please implement to set a dafult value for new columns that are defined as 'notNull'?

**Comment by yuweiguocn** [comment]
I'm sorry.You can see this https://github.com/greenrobot/greenDAO/issues/17.

**Comment by Thamizhan** [comment]
@yuweiguocn that link is not helpful.

Say when I have new fields added which is int, create table query make it as NOT NULL, so when I try to migrate values from old table to new one, it only copy old columns values and skipping new columns, in this case I'm getting 

> NOT NULL constraint failed

So we should have default values, or make new fields nullable even with integer fields.

**Comment by yuweiguocn** [comment]
@Thamizhan please use Integer instead of int ,Boolean instead of boolean,and so on.GreenDao generated sql won't add not null constraint by use this way.

**Comment by Thamizhan** [comment]
@yuweiguocn Thanks for prompt response, I'll try this method and update here.
