### ISSUE TITLE
在我的表里有数据的情况下，增加字段不成功，

### ISSUE THREAD

**Issue by 836986836** [yuweiguocn/GreenDaoUpgradeHelper#23]
restoreData（）方法里面 转移数据的时候，抛出异常，
 android.database.sqlite.SQLiteConstraintException: 表.增加的字段 may not be NULL (code 19)
数据转移失败，新表为空 ，temp表 未删除， 如何解决 啊 大神！！！！！

**Comment by jact-hz** [comment]
你开启debug看看报什么错
我这面报的错 
加上compile 'net.zetetic:android-database-sqlcipher:3.5.6' 
这个库成功了。但是包会增加8M 好些个.so文件

**Comment by yuweiguocn** [comment]
@836986836 抱歉，来晚了 ，你可以看看这个 https://github.com/greenrobot/greenDAO/issues/17
这个是由于greenDAO 3.0 生成的字段默认添加了非空约束。
