### ISSUE TITLE
修改MyDaoGenerator的表结构之后，怎么让他重新生成dao文件

### ISSUE THREAD

**Issue by ysq1051838264** [yuweiguocn/GreenDaoUpgradeHelper#24]
改变MyDaoGenerator的表结构之后，怎么让他重新生成dao文件

**Comment by ysq1051838264** [comment]
Error:Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

**Comment by yuweiguocn** [comment]
右键运行
![image](https://cloud.githubusercontent.com/assets/4308480/25884201/3ad034f6-3583-11e7-809c-f3f4323665af.png)
