### ISSUE TITLE
Failed to resolve:com.github.yuweiguocn:GreenDaoUpgradeHelper:V2.0.0

### ISSUE THREAD

**Issue by fuyuguang** [yuweiguocn/GreenDaoUpgradeHelper#35]
![](http://ota9h9es5.bkt.clouddn.com/17-11-9/79825072.jpg)

![](http://ota9h9es5.bkt.clouddn.com/17-11-9/15600696.jpg)

Please help to resolve this problem. Thanks in advance

**Comment by TYUpya** [comment]
请问这个问题解决了吗？Has the problem been solved?
