### ISSUE TITLE
数据库升级：compile 'com.github.yuweiguocn:GreenDaoUpgradeHelper:v2.0.1'  

### ISSUE THREAD

**Issue by Iamrookie** [yuweiguocn/GreenDaoUpgradeHelper#42]
compile 'com.github.yuweiguocn:GreenDaoUpgradeHelper:v2.0.1'   这个依赖不上  老哥  出了什么问题呢

**Comment by yuweiguocn** [comment]
添加下jitpack仓库
```
	allprojects {
		repositories {
			...
			maven { url "https://jitpack.io" }
		}
	}
```

**Comment by Iamrookie** [comment]
加了这个也不行，我的是如下所示
buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
报错提示：
Error:(40, 13) Failed to resolve: com.github.yuweiguocn:GreenDaoUpgradeHelper:v2.0.1

然后我直接用了你那个类的源码导入后，发现改了字段升级数据库版本后，数据库表的数据丢失了！这样升级就丢数据，是我哪边还操作的有问题吗 ？我操作是这样 比如新增了某表的一个字段后，然后修改schemaVersion  版本号+1  这样，结果表示数据丢失。有解决办法吗？还是我操作错误 ？

**Comment by Iamrookie** [comment]
老哥  greendao 3.2 试过用你那个帮助类源码导入本地，实现MigrationHelper.ReCreateAllTableListener是直接升级一次直接数据丢失，然后用那个一句话的，都是数据必丢失。然后发现一个问题， 就是升级是删除字段的时候  后续增加的对象，删除的字段依然还在。

**Comment by yuweiguocn** [comment]
删除字段操作暂时不支持!
