### ISSUE TITLE
删掉一个字段，表结构没有变化

### ISSUE THREAD

**Issue by MaXiaoWu2015** [yuweiguocn/GreenDaoUpgradeHelper#5]
你好，我照着文档把库引入后，我去掉了表的一个字段，在运行，用sqlite命令查看表结构，发现该字段还在，不知道这是什么情况呢

**Comment by yuweiguocn** [comment]
你好，目前还不支持删除表字段，删除表字段的情况比较少，如果你有兴趣添加此功能，可以提交PR。
