### ISSUE TITLE
the overload method of migrate bug

### ISSUE THREAD

**Issue by Wingge** [yuweiguocn/GreenDaoUpgradeHelper#51]
1.method: migrate(Database database, Class>... daoClasses)
error line:ReCreateAllTableListener listener = weakListener.get();
if call this method ,the weaklistenner is null.it only init in the others two overload method.

2.in this method :
if (listener != null) {
listener.onDropAllTables(database, true);
printLog("【Drop all table by listener】");
listener.onCreateAllTables(database, false);
printLog("【Create all table by listener】");
} else {
dropAllTables(database, true, daoClasses);
createAllTables(database, false, daoClasses);
}
but the listener can not be null!because the param access modifiers is NOTNULL of the method migrate's.

so,the greendao can not upgrade using migrate(Database database, Class>... daoClasses)

**Comment by yuweiguocn** [comment]
Thank you very much.
1.fixed.
2.when listener is null,will by reflect resolve.

**Comment by ghost** [comment]
> Thank you very much.
> 1.fixed.
> 2.when listener is null,will by reflect resolve.

1.    ReCreateAllTableListener回调中
**仅凭 
 DaoMaster.createAllTables(db, ifNotExists);
 DaoMaster.dropAllTables(db, ifExists);
升级，会把不需要升级的表也删除了**     
2.反射不会，但反射需要配额外的混淆规则，release可能会出现一些问题
