### ISSUE TITLE
表增加字段后，在onUpgrade方法里需要写alter table语句增加字段么

### ISSUE THREAD

**Issue by yahier** [yuweiguocn/GreenDaoUpgradeHelper#55]
你好，题目描述的问题，我测试是要的，但不是十分确定。是否需要增加

String sql = "alter table OFF_LINE_ORDER add uploadSuccessTime long default 0";
db.execSQL(sql);

**Comment by yuweiguocn** [comment]
不需要的，这个库就是帮你做这件事的。

**Comment by soxunyi** [comment]
@yuweiguocn 如果yahier的sql语句default 0需要是default 100呢。需要怎么处理呢。感谢

`alter table OFF_LINE_ORDER add uploadSuccessTime long default 100`
