### ISSUE TITLE
当新表存在字段约束为 NOT NULL，而旧表不存在该字段时，导致旧数据 restore 失败，进而导致数据被清除

### ISSUE THREAD

**Issue by jefshi** [yuweiguocn/GreenDaoUpgradeHelper#56]
如题，报错信息为旧数据 restore 时，执行 REPLACE INTO * SELECT * 时，SQLite 提示字段值不能为 NULL

**Comment by jefshi** [comment]
已经解决了，并 commit 和 pull requests

**Comment by jefshi** [comment]
如果新表字段约束为 UNIQUE 时，仍然可能导致的旧数据 restore 的SQL执行失败

**Comment by yuweiguocn** [comment]
非常感谢
