### ISSUE TITLE
关于数据库升级，数据迁移与删除，数据表创建

### ISSUE THREAD

**Issue by VeiZhang** [yuweiguocn/GreenDaoUpgradeHelper#59]
比如A、B、C三张表，我现在想升级数据库，只迁移A和B的数据，但是C的数据不迁移，我想把C的数据删除，并且重新创建表C，可以做到这种吗？

**Comment by yuweiguocn** [comment]
可以在自动升级完成后，自己手动添加代码处理额外的操作，如：重新创建表C等。
