### ISSUE TITLE
添加之后有异常 java.util.zip.ZipException

### ISSUE THREAD

**Issue by Roing** [yuweiguocn/GreenDaoUpgradeHelper#7]
添加这个库之后,运行在Android5.0以下的版本都会报出这个错误:
Error:Execution failed for task ':app:transformClassesWithJarMergingForEduchatDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: de/greenrobot/dao/AbstractDao.class

**Comment by yuweiguocn** [comment]
请使用版本1.0.1或将greendao的版本升级到3.0，详见README说明。

**Comment by Roing** [comment]
就是是用1.0.1出现的问题,现在项目无法升级到greendao 3.0

**Comment by yuweiguocn** [comment]
@Roing 那就是你重复引用greendao类库了
